"""Convenience star-import module mirroring the Rust crate's ``prelude``.

Typical usage:

    from rushaudio.prelude import *
"""

from . import (
    AudioCodec,
    AudioLevels,
    Connection,
    ConnectionPool,
    ConnectionState,
    FecEncoder,
    Handshake,
    HandshakeRole,
    HandshakeState,
    JitterBuffer,
    JitterStats,
    Metadata,
    MetadataBuilder,
    MetadataEntry,
    MetadataMap,
    Packet,
    PacketHeader,
    PacketType,
    SessionManager,
    StreamConfig,
    StreamStats,
    UdpTransport,
)
from . import DEFAULT_PORT, VERSION, create_client, create_server
from .constants import (
    HEADER_SIZE,
    MAX_PACKET_SIZE,
    MAX_PAYLOAD_SIZE,
    META_ALBUM,
    META_ARTIST,
    META_BITRATE,
    META_CHANNELS,
    META_CODEC_INFO,
    META_CUSTOM_BASE,
    META_DURATION_MS,
    META_GENRE,
    META_SAMPLE_RATE,
    META_SSRC,
    META_STREAM_TITLE,
    META_STREAM_URL,
    META_TRACK_TITLE,
    PROTOCOL_MAGIC,
    PROTOCOL_VERSION,
)

__all__ = [
    "AudioCodec",
    "AudioLevels",
    "Connection",
    "ConnectionPool",
    "ConnectionState",
    "FecEncoder",
    "Handshake",
    "HandshakeRole",
    "HandshakeState",
    "JitterBuffer",
    "JitterStats",
    "Metadata",
    "MetadataBuilder",
    "MetadataEntry",
    "MetadataMap",
    "Packet",
    "PacketHeader",
    "PacketType",
    "SessionManager",
    "StreamConfig",
    "StreamStats",
    "UdpTransport",
    "DEFAULT_PORT",
    "VERSION",
    "create_server",
    "create_client",
    "HEADER_SIZE",
    "MAX_PACKET_SIZE",
    "MAX_PAYLOAD_SIZE",
    "META_SSRC",
    "META_TRACK_TITLE",
    "META_ARTIST",
    "META_ALBUM",
    "META_GENRE",
    "META_SAMPLE_RATE",
    "META_CHANNELS",
    "META_CODEC_INFO",
    "META_BITRATE",
    "META_DURATION_MS",
    "META_STREAM_TITLE",
    "META_STREAM_URL",
    "META_CUSTOM_BASE",
    "PROTOCOL_MAGIC",
    "PROTOCOL_VERSION",
]